ChampionsTown_MapScripts::
	.byte 0


# 3 "data/maps/ChampionsTown/scripts.pory"

# 4 "data/maps/ChampionsTown/scripts.pory"
ChampionsTown_EventScript_DomeTentSign::
# 5 "data/maps/ChampionsTown/scripts.pory"
	msgbox ChampionsTown_Text_DomeTentSign, MSGBOX_SIGN
# 6 "data/maps/ChampionsTown/scripts.pory"
	end
# 7 "data/maps/ChampionsTown/scripts.pory"

# 8 "data/maps/ChampionsTown/scripts.pory"
ChampionsTown_EventScript_PikeTentSign::
# 9 "data/maps/ChampionsTown/scripts.pory"
	msgbox ChampionsTown_Text_PikeTentSign, MSGBOX_SIGN
# 10 "data/maps/ChampionsTown/scripts.pory"
	end
# 11 "data/maps/ChampionsTown/scripts.pory"

# 12 "data/maps/ChampionsTown/scripts.pory"
ChampionsTown_EventScript_PyramidTentSign::
# 13 "data/maps/ChampionsTown/scripts.pory"
	msgbox ChampionsTown_Text_PyramidTentSign, MSGBOX_SIGN
# 14 "data/maps/ChampionsTown/scripts.pory"
	end
# 15 "data/maps/ChampionsTown/scripts.pory"

# 16 "data/maps/ChampionsTown/scripts.pory"
ChampionsTown_Text_DomeTentSign:
# 17 "data/maps/ChampionsTown/scripts.pory"
	.string "CHAMPIONS DOME TENT\p"
# 18 "data/maps/ChampionsTown/scripts.pory"
	.string "A miniature Battle Dome challenge.$"
# 19 "data/maps/ChampionsTown/scripts.pory"

# 20 "data/maps/ChampionsTown/scripts.pory"
ChampionsTown_Text_PikeTentSign:
# 21 "data/maps/ChampionsTown/scripts.pory"
	.string "CHAMPIONS PIKE TENT\p"
# 22 "data/maps/ChampionsTown/scripts.pory"
	.string "A miniature Battle Pike challenge.$"
# 23 "data/maps/ChampionsTown/scripts.pory"

# 24 "data/maps/ChampionsTown/scripts.pory"
ChampionsTown_Text_PyramidTentSign:
# 25 "data/maps/ChampionsTown/scripts.pory"
	.string "CHAMPIONS PYRAMID TENT\p"
# 26 "data/maps/ChampionsTown/scripts.pory"
	.string "A miniature Battle Pyramid challenge.$"
